--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Terpzz/PocKit
build-by-default: true
$options = [new MenuOption("Rename") ];

if ($kit["private"] === true) {
    $ifPrivatePermDisplay = "This kit can only be used by players with the permission pockit.kit." . strtolower(str_replace(" ", "_",$kitId));
    $options[]=new MenuOption("Private: ". TextFormat::GREEN . "true");
} else {
    $ifPrivatePermDisplay = "";
    $options[]=new MenuOption("Private: ". TextFormat::RED . "false");
}
...
