--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Terpzz/PocKit
build-by-default: true
branches:
- main
projects:
  Pockit:
    path: ""
    libs:
      - src: Muqsit/InvMenu/InvMenu
        version: 4.3.8
      - src: dktapps-pm-pl/pmforms/pmforms
        version: ~2.0.0
...
